apiVersion: apps/v1
kind: Deployment
metadata:
  name: kustomization-write-target
spec:
  replicas: 1
  template:
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - name: nginx
        image: quay.io/varsha/nginx-unprivileged:1.31.0
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]