resources:
  - deployment.yaml
labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app: kustomization-write-target
images:
  - name: quay.io/varsha/nginx-unprivileged
    newName: quay.io/varsha/nginx-unprivileged
    newTag: 1.31.2
