# values-0.yaml
global:
  compatibility:
    openshift:
      adaptSecurityContext: auto

image:
  registry: docker.io
  repository: bitnamilegacy/nginx
  tag: 1.27.1

podSecurityContext:
  fsGroup: null
containerSecurityContext:
  runAsUser: null