# values-0.yaml
global:
  compatibility:
    openshift:
      adaptSecurityContext: auto

image:
  registry: docker.io
  repository: nginxinc/nginx-unprivileged
  tag: 1.31.1

podSecurityContext:
  fsGroup: null
containerSecurityContext:
  runAsUser: null