apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: kustomize-helmvalues
  namespace: openshift-gitops
spec:
  applicationRefs:
    - namePattern: "kustomize-helmvalues"
      images:
        - alias: "nginx-unprivileged"
          imageName: "quay.io/varsha/nginx-unprivileged:1.31.x"
          commonUpdateSettings:
            updateStrategy: "semver"
            forceUpdate: false
            pullSecret: "pullsecret:openshift-gitops/quay-pull-secret"
          manifestTargets:
            kustomize:
              name: "quay.io/varsha/nginx-unprivileged"
  writeBackConfig:
    method: "git:secret:openshift-gitops/git-creds"
    gitConfig:
      repository: "https://github.com/varshab1210/image-updater-examples.git"
      branch: "webhook"
      writeBackTarget: "kustomization:/kustomization-write-target/source"
      pullRequest:
        github: {}
