apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: kustomize-helmvalues
  namespace: openshift-gitops
spec:
  applicationRefs:
    - namePattern: "kustomize-helmvalues"
      images:
        - alias: "nginx"
          imageName: "docker.io/nginxinc/nginx-unprivileged:1.31.x"
          commonUpdateSettings:
            updateStrategy: "semver"
            forceUpdate: false
          manifestTargets:
            helm:
              name: "image.repository"
              tag: "image.tag"
  writeBackConfig:
    method: "git:secret:openshift-gitops/git-creds"
    gitConfig:
      repository: "https://github.com/varshab1210/image-updater-examples.git"
      branch: "test-2"
      writeBackTarget: "helmvalues:/kustomize-helmvalues/source2/values.yaml"
